plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/npm"
  - - "@semantic-release/changelog"
    - changelogFile: "docs/CHANGELOG.md"
  - - "@semantic-release/git"
    - assets:
        - docs.md
        - package.json
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - "@semantic-release/github"
