name: Tests

on: [push]

#

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        run: |
          pwd
          cd .k8s
          yarn --frozen-lockfile --perfer-offline

      - name: Run tests
        run: |
          pwd
          cd .k8s
          yarn test
