name: Tests

on: [push, pull_request]

#

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        run: yarn --frozen-lockfile --perfer-offline

      - name: Run tests
        run: yarn test
